Create zh_tw.json
Avanatiker/WorldTools pull request #49
Opened 2024-10-20 16:03 UTC by yichifauzi

Add Traditional Chinese localization

2024-11-10 11:07 UTC, notlin4 requested changes

2024-11-10 11:07 UTC, notlin4 commented on common/src/main/resources/assets/worldtools/lang/zh_tw.json
> +  "text.autoconfig.worldtools.option.render.fromCacheLoadedEntityColor": "從快取載入的實體顏色 (RGB 十六進位)",
```suggestion
  "text.autoconfig.worldtools.option.render.accentColor": "強調色（RGB 十六進位）",
  "text.autoconfig.worldtools.option.render.captureBarColor": "擷取資訊列顏色（RGB 十六進位）",
  "text.autoconfig.worldtools.option.render.captureBarStyle": "擷取資訊列樣式",
  "text.autoconfig.worldtools.option.render.unscannedContainerColor": "遺漏容器顏色（RGB 十六進位）",
  "text.autoconfig.worldtools.option.render.fromCacheLoadedContainerColor": "從快取載入的容器顏色 (RGB 十六進位）",
  "text.autoconfig.worldtools.option.render.unscannedEntityColor": "遺漏實體顏色（RGB 十六進位）",
  "text.autoconfig.worldtools.option.render.fromCacheLoadedEntityColor": "從快取載入的實體顏色（RGB 十六進位）",
```

2024-11-10 11:07 UTC, notlin4 commented on common/src/main/resources/assets/worldtools/lang/zh_tw.json
> +  "text.autoconfig.worldtools.option.render.progressBarTimeout": "進度條逾時 (毫秒)",
```suggestion
  "text.autoconfig.worldtools.option.render.progressBarTimeout": "進度條逾時（毫秒）",
```

2024-11-10 11:07 UTC, notlin4 commented on common/src/main/resources/assets/worldtools/lang/zh_tw.json
> +  "worldtools.gui.capture.existing_world_confirm.message": "已存在名為 \"%s\" 的儲存檔案。要覆蓋它嗎？（將會與現有資料合併）",
```suggestion
  "worldtools.gui.capture.existing_world_confirm.message": "已存在名為「%s」的儲存檔案。要覆蓋它嗎？（將與現有資料合併）",
```

2024-11-10 11:07 UTC, notlin4 commented on common/src/main/resources/assets/worldtools/lang/zh_tw.json
> +  "worldtools.log.error.failed_to_save_level": "無法儲存 \"%s\" 的 level.dat！（錯誤：%s）",
```suggestion
  "worldtools.log.error.failed_to_create_session": "無法為「%s」建立工作階段！（錯誤：%s）",
  "worldtools.log.error.failed_to_save_level": "無法儲存「%s」的 level.dat！（錯誤：%s）",
```

2024-11-10 11:07 UTC, notlin4 commented on common/src/main/resources/assets/worldtools/lang/zh_tw.json
> +  "worldtools.log.error.world_name_too_long": "世界名稱 \"%s\" 太長！（最多 %d 個字元）",
```suggestion
  "worldtools.log.error.world_name_too_long": "世界名稱「%s」太長！（最多 %d 個字元）",
```

2024-11-10 11:07 UTC, notlin4 commented on common/src/main/resources/assets/worldtools/lang/zh_tw.json
> +  "worldtools.log.info.singleplayer_capture": "實驗性：在單人遊戲中擷取是實驗性的，可能無法按預期工作！",
```suggestion
  "worldtools.log.info.singleplayer_capture": "實驗性：在單人遊戲中擷取是實驗性的，可能無法按預期運作！",
```

2024-11-10 11:07 UTC, notlin4 commented on common/src/main/resources/assets/worldtools/lang/zh_tw.json
> +  "worldtools.capture.click_to_open": "%s（點擊以開啟）",
```suggestion
  "worldtools.capture.click_to_open": "%s（按這裡開啟）",
```

2024-11-15 00:06 UTC, Avanatiker commented
谢谢 :3

2024-11-15 00:08 UTC, merged